// <auto-generated />
using EldenRingArKalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EldenRingArKalculator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EldenRingArKalculator.Models.Attack", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Arc0")
                        .HasColumnType("real");

                    b.Property<float>("Arc1")
                        .HasColumnType("real");

                    b.Property<float>("Arc10")
                        .HasColumnType("real");

                    b.Property<float>("Arc11")
                        .HasColumnType("real");

                    b.Property<float>("Arc12")
                        .HasColumnType("real");

                    b.Property<float>("Arc13")
                        .HasColumnType("real");

                    b.Property<float>("Arc14")
                        .HasColumnType("real");

                    b.Property<float>("Arc15")
                        .HasColumnType("real");

                    b.Property<float>("Arc16")
                        .HasColumnType("real");

                    b.Property<float>("Arc17")
                        .HasColumnType("real");

                    b.Property<float>("Arc18")
                        .HasColumnType("real");

                    b.Property<float>("Arc19")
                        .HasColumnType("real");

                    b.Property<float>("Arc2")
                        .HasColumnType("real");

                    b.Property<float>("Arc20")
                        .HasColumnType("real");

                    b.Property<float>("Arc21")
                        .HasColumnType("real");

                    b.Property<float>("Arc22")
                        .HasColumnType("real");

                    b.Property<float>("Arc23")
                        .HasColumnType("real");

                    b.Property<float>("Arc24")
                        .HasColumnType("real");

                    b.Property<float>("Arc25")
                        .HasColumnType("real");

                    b.Property<float>("Arc3")
                        .HasColumnType("real");

                    b.Property<float>("Arc4")
                        .HasColumnType("real");

                    b.Property<float>("Arc5")
                        .HasColumnType("real");

                    b.Property<float>("Arc6")
                        .HasColumnType("real");

                    b.Property<float>("Arc7")
                        .HasColumnType("real");

                    b.Property<float>("Arc8")
                        .HasColumnType("real");

                    b.Property<float>("Arc9")
                        .HasColumnType("real");

                    b.Property<float>("Dex0")
                        .HasColumnType("real");

                    b.Property<float>("Dex1")
                        .HasColumnType("real");

                    b.Property<float>("Dex10")
                        .HasColumnType("real");

                    b.Property<float>("Dex11")
                        .HasColumnType("real");

                    b.Property<float>("Dex12")
                        .HasColumnType("real");

                    b.Property<float>("Dex13")
                        .HasColumnType("real");

                    b.Property<float>("Dex14")
                        .HasColumnType("real");

                    b.Property<float>("Dex15")
                        .HasColumnType("real");

                    b.Property<float>("Dex16")
                        .HasColumnType("real");

                    b.Property<float>("Dex17")
                        .HasColumnType("real");

                    b.Property<float>("Dex18")
                        .HasColumnType("real");

                    b.Property<float>("Dex19")
                        .HasColumnType("real");

                    b.Property<float>("Dex2")
                        .HasColumnType("real");

                    b.Property<float>("Dex20")
                        .HasColumnType("real");

                    b.Property<float>("Dex21")
                        .HasColumnType("real");

                    b.Property<float>("Dex22")
                        .HasColumnType("real");

                    b.Property<float>("Dex23")
                        .HasColumnType("real");

                    b.Property<float>("Dex24")
                        .HasColumnType("real");

                    b.Property<float>("Dex25")
                        .HasColumnType("real");

                    b.Property<float>("Dex3")
                        .HasColumnType("real");

                    b.Property<float>("Dex4")
                        .HasColumnType("real");

                    b.Property<float>("Dex5")
                        .HasColumnType("real");

                    b.Property<float>("Dex6")
                        .HasColumnType("real");

                    b.Property<float>("Dex7")
                        .HasColumnType("real");

                    b.Property<float>("Dex8")
                        .HasColumnType("real");

                    b.Property<float>("Dex9")
                        .HasColumnType("real");

                    b.Property<float>("Fai0")
                        .HasColumnType("real");

                    b.Property<float>("Fai1")
                        .HasColumnType("real");

                    b.Property<float>("Fai10")
                        .HasColumnType("real");

                    b.Property<float>("Fai11")
                        .HasColumnType("real");

                    b.Property<float>("Fai12")
                        .HasColumnType("real");

                    b.Property<float>("Fai13")
                        .HasColumnType("real");

                    b.Property<float>("Fai14")
                        .HasColumnType("real");

                    b.Property<float>("Fai15")
                        .HasColumnType("real");

                    b.Property<float>("Fai16")
                        .HasColumnType("real");

                    b.Property<float>("Fai17")
                        .HasColumnType("real");

                    b.Property<float>("Fai18")
                        .HasColumnType("real");

                    b.Property<float>("Fai19")
                        .HasColumnType("real");

                    b.Property<float>("Fai2")
                        .HasColumnType("real");

                    b.Property<float>("Fai20")
                        .HasColumnType("real");

                    b.Property<float>("Fai21")
                        .HasColumnType("real");

                    b.Property<float>("Fai22")
                        .HasColumnType("real");

                    b.Property<float>("Fai23")
                        .HasColumnType("real");

                    b.Property<float>("Fai24")
                        .HasColumnType("real");

                    b.Property<float>("Fai25")
                        .HasColumnType("real");

                    b.Property<float>("Fai3")
                        .HasColumnType("real");

                    b.Property<float>("Fai4")
                        .HasColumnType("real");

                    b.Property<float>("Fai5")
                        .HasColumnType("real");

                    b.Property<float>("Fai6")
                        .HasColumnType("real");

                    b.Property<float>("Fai7")
                        .HasColumnType("real");

                    b.Property<float>("Fai8")
                        .HasColumnType("real");

                    b.Property<float>("Fai9")
                        .HasColumnType("real");

                    b.Property<float>("Int0")
                        .HasColumnType("real");

                    b.Property<float>("Int1")
                        .HasColumnType("real");

                    b.Property<float>("Int10")
                        .HasColumnType("real");

                    b.Property<float>("Int11")
                        .HasColumnType("real");

                    b.Property<float>("Int12")
                        .HasColumnType("real");

                    b.Property<float>("Int13")
                        .HasColumnType("real");

                    b.Property<float>("Int14")
                        .HasColumnType("real");

                    b.Property<float>("Int15")
                        .HasColumnType("real");

                    b.Property<float>("Int16")
                        .HasColumnType("real");

                    b.Property<float>("Int17")
                        .HasColumnType("real");

                    b.Property<float>("Int18")
                        .HasColumnType("real");

                    b.Property<float>("Int19")
                        .HasColumnType("real");

                    b.Property<float>("Int2")
                        .HasColumnType("real");

                    b.Property<float>("Int20")
                        .HasColumnType("real");

                    b.Property<float>("Int21")
                        .HasColumnType("real");

                    b.Property<float>("Int22")
                        .HasColumnType("real");

                    b.Property<float>("Int23")
                        .HasColumnType("real");

                    b.Property<float>("Int24")
                        .HasColumnType("real");

                    b.Property<float>("Int25")
                        .HasColumnType("real");

                    b.Property<float>("Int3")
                        .HasColumnType("real");

                    b.Property<float>("Int4")
                        .HasColumnType("real");

                    b.Property<float>("Int5")
                        .HasColumnType("real");

                    b.Property<float>("Int6")
                        .HasColumnType("real");

                    b.Property<float>("Int7")
                        .HasColumnType("real");

                    b.Property<float>("Int8")
                        .HasColumnType("real");

                    b.Property<float>("Int9")
                        .HasColumnType("real");

                    b.Property<float>("Str0")
                        .HasColumnType("real");

                    b.Property<float>("Str1")
                        .HasColumnType("real");

                    b.Property<float>("Str10")
                        .HasColumnType("real");

                    b.Property<float>("Str11")
                        .HasColumnType("real");

                    b.Property<float>("Str12")
                        .HasColumnType("real");

                    b.Property<float>("Str13")
                        .HasColumnType("real");

                    b.Property<float>("Str14")
                        .HasColumnType("real");

                    b.Property<float>("Str15")
                        .HasColumnType("real");

                    b.Property<float>("Str16")
                        .HasColumnType("real");

                    b.Property<float>("Str17")
                        .HasColumnType("real");

                    b.Property<float>("Str18")
                        .HasColumnType("real");

                    b.Property<float>("Str19")
                        .HasColumnType("real");

                    b.Property<float>("Str2")
                        .HasColumnType("real");

                    b.Property<float>("Str20")
                        .HasColumnType("real");

                    b.Property<float>("Str21")
                        .HasColumnType("real");

                    b.Property<float>("Str22")
                        .HasColumnType("real");

                    b.Property<float>("Str23")
                        .HasColumnType("real");

                    b.Property<float>("Str24")
                        .HasColumnType("real");

                    b.Property<float>("Str25")
                        .HasColumnType("real");

                    b.Property<float>("Str3")
                        .HasColumnType("real");

                    b.Property<float>("Str4")
                        .HasColumnType("real");

                    b.Property<float>("Str5")
                        .HasColumnType("real");

                    b.Property<float>("Str6")
                        .HasColumnType("real");

                    b.Property<float>("Str7")
                        .HasColumnType("real");

                    b.Property<float>("Str8")
                        .HasColumnType("real");

                    b.Property<float>("Str9")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("EldenRingArKalculator.Models.Scaling", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Arc0")
                        .HasColumnType("real");

                    b.Property<float>("Arc1")
                        .HasColumnType("real");

                    b.Property<float>("Arc10")
                        .HasColumnType("real");

                    b.Property<float>("Arc11")
                        .HasColumnType("real");

                    b.Property<float>("Arc12")
                        .HasColumnType("real");

                    b.Property<float>("Arc13")
                        .HasColumnType("real");

                    b.Property<float>("Arc14")
                        .HasColumnType("real");

                    b.Property<float>("Arc15")
                        .HasColumnType("real");

                    b.Property<float>("Arc16")
                        .HasColumnType("real");

                    b.Property<float>("Arc17")
                        .HasColumnType("real");

                    b.Property<float>("Arc18")
                        .HasColumnType("real");

                    b.Property<float>("Arc19")
                        .HasColumnType("real");

                    b.Property<float>("Arc2")
                        .HasColumnType("real");

                    b.Property<float>("Arc20")
                        .HasColumnType("real");

                    b.Property<float>("Arc21")
                        .HasColumnType("real");

                    b.Property<float>("Arc22")
                        .HasColumnType("real");

                    b.Property<float>("Arc23")
                        .HasColumnType("real");

                    b.Property<float>("Arc24")
                        .HasColumnType("real");

                    b.Property<float>("Arc25")
                        .HasColumnType("real");

                    b.Property<float>("Arc3")
                        .HasColumnType("real");

                    b.Property<float>("Arc4")
                        .HasColumnType("real");

                    b.Property<float>("Arc5")
                        .HasColumnType("real");

                    b.Property<float>("Arc6")
                        .HasColumnType("real");

                    b.Property<float>("Arc7")
                        .HasColumnType("real");

                    b.Property<float>("Arc8")
                        .HasColumnType("real");

                    b.Property<float>("Arc9")
                        .HasColumnType("real");

                    b.Property<float>("Dex0")
                        .HasColumnType("real");

                    b.Property<float>("Dex1")
                        .HasColumnType("real");

                    b.Property<float>("Dex10")
                        .HasColumnType("real");

                    b.Property<float>("Dex11")
                        .HasColumnType("real");

                    b.Property<float>("Dex12")
                        .HasColumnType("real");

                    b.Property<float>("Dex13")
                        .HasColumnType("real");

                    b.Property<float>("Dex14")
                        .HasColumnType("real");

                    b.Property<float>("Dex15")
                        .HasColumnType("real");

                    b.Property<float>("Dex16")
                        .HasColumnType("real");

                    b.Property<float>("Dex17")
                        .HasColumnType("real");

                    b.Property<float>("Dex18")
                        .HasColumnType("real");

                    b.Property<float>("Dex19")
                        .HasColumnType("real");

                    b.Property<float>("Dex2")
                        .HasColumnType("real");

                    b.Property<float>("Dex20")
                        .HasColumnType("real");

                    b.Property<float>("Dex21")
                        .HasColumnType("real");

                    b.Property<float>("Dex22")
                        .HasColumnType("real");

                    b.Property<float>("Dex23")
                        .HasColumnType("real");

                    b.Property<float>("Dex24")
                        .HasColumnType("real");

                    b.Property<float>("Dex25")
                        .HasColumnType("real");

                    b.Property<float>("Dex3")
                        .HasColumnType("real");

                    b.Property<float>("Dex4")
                        .HasColumnType("real");

                    b.Property<float>("Dex5")
                        .HasColumnType("real");

                    b.Property<float>("Dex6")
                        .HasColumnType("real");

                    b.Property<float>("Dex7")
                        .HasColumnType("real");

                    b.Property<float>("Dex8")
                        .HasColumnType("real");

                    b.Property<float>("Dex9")
                        .HasColumnType("real");

                    b.Property<float>("Fai0")
                        .HasColumnType("real");

                    b.Property<float>("Fai1")
                        .HasColumnType("real");

                    b.Property<float>("Fai10")
                        .HasColumnType("real");

                    b.Property<float>("Fai11")
                        .HasColumnType("real");

                    b.Property<float>("Fai12")
                        .HasColumnType("real");

                    b.Property<float>("Fai13")
                        .HasColumnType("real");

                    b.Property<float>("Fai14")
                        .HasColumnType("real");

                    b.Property<float>("Fai15")
                        .HasColumnType("real");

                    b.Property<float>("Fai16")
                        .HasColumnType("real");

                    b.Property<float>("Fai17")
                        .HasColumnType("real");

                    b.Property<float>("Fai18")
                        .HasColumnType("real");

                    b.Property<float>("Fai19")
                        .HasColumnType("real");

                    b.Property<float>("Fai2")
                        .HasColumnType("real");

                    b.Property<float>("Fai20")
                        .HasColumnType("real");

                    b.Property<float>("Fai21")
                        .HasColumnType("real");

                    b.Property<float>("Fai22")
                        .HasColumnType("real");

                    b.Property<float>("Fai23")
                        .HasColumnType("real");

                    b.Property<float>("Fai24")
                        .HasColumnType("real");

                    b.Property<float>("Fai25")
                        .HasColumnType("real");

                    b.Property<float>("Fai3")
                        .HasColumnType("real");

                    b.Property<float>("Fai4")
                        .HasColumnType("real");

                    b.Property<float>("Fai5")
                        .HasColumnType("real");

                    b.Property<float>("Fai6")
                        .HasColumnType("real");

                    b.Property<float>("Fai7")
                        .HasColumnType("real");

                    b.Property<float>("Fai8")
                        .HasColumnType("real");

                    b.Property<float>("Fai9")
                        .HasColumnType("real");

                    b.Property<float>("Int0")
                        .HasColumnType("real");

                    b.Property<float>("Int1")
                        .HasColumnType("real");

                    b.Property<float>("Int10")
                        .HasColumnType("real");

                    b.Property<float>("Int11")
                        .HasColumnType("real");

                    b.Property<float>("Int12")
                        .HasColumnType("real");

                    b.Property<float>("Int13")
                        .HasColumnType("real");

                    b.Property<float>("Int14")
                        .HasColumnType("real");

                    b.Property<float>("Int15")
                        .HasColumnType("real");

                    b.Property<float>("Int16")
                        .HasColumnType("real");

                    b.Property<float>("Int17")
                        .HasColumnType("real");

                    b.Property<float>("Int18")
                        .HasColumnType("real");

                    b.Property<float>("Int19")
                        .HasColumnType("real");

                    b.Property<float>("Int2")
                        .HasColumnType("real");

                    b.Property<float>("Int20")
                        .HasColumnType("real");

                    b.Property<float>("Int21")
                        .HasColumnType("real");

                    b.Property<float>("Int22")
                        .HasColumnType("real");

                    b.Property<float>("Int23")
                        .HasColumnType("real");

                    b.Property<float>("Int24")
                        .HasColumnType("real");

                    b.Property<float>("Int25")
                        .HasColumnType("real");

                    b.Property<float>("Int3")
                        .HasColumnType("real");

                    b.Property<float>("Int4")
                        .HasColumnType("real");

                    b.Property<float>("Int5")
                        .HasColumnType("real");

                    b.Property<float>("Int6")
                        .HasColumnType("real");

                    b.Property<float>("Int7")
                        .HasColumnType("real");

                    b.Property<float>("Int8")
                        .HasColumnType("real");

                    b.Property<float>("Int9")
                        .HasColumnType("real");

                    b.Property<float>("Str0")
                        .HasColumnType("real");

                    b.Property<float>("Str1")
                        .HasColumnType("real");

                    b.Property<float>("Str10")
                        .HasColumnType("real");

                    b.Property<float>("Str11")
                        .HasColumnType("real");

                    b.Property<float>("Str12")
                        .HasColumnType("real");

                    b.Property<float>("Str13")
                        .HasColumnType("real");

                    b.Property<float>("Str14")
                        .HasColumnType("real");

                    b.Property<float>("Str15")
                        .HasColumnType("real");

                    b.Property<float>("Str16")
                        .HasColumnType("real");

                    b.Property<float>("Str17")
                        .HasColumnType("real");

                    b.Property<float>("Str18")
                        .HasColumnType("real");

                    b.Property<float>("Str19")
                        .HasColumnType("real");

                    b.Property<float>("Str2")
                        .HasColumnType("real");

                    b.Property<float>("Str20")
                        .HasColumnType("real");

                    b.Property<float>("Str21")
                        .HasColumnType("real");

                    b.Property<float>("Str22")
                        .HasColumnType("real");

                    b.Property<float>("Str23")
                        .HasColumnType("real");

                    b.Property<float>("Str24")
                        .HasColumnType("real");

                    b.Property<float>("Str25")
                        .HasColumnType("real");

                    b.Property<float>("Str3")
                        .HasColumnType("real");

                    b.Property<float>("Str4")
                        .HasColumnType("real");

                    b.Property<float>("Str5")
                        .HasColumnType("real");

                    b.Property<float>("Str6")
                        .HasColumnType("real");

                    b.Property<float>("Str7")
                        .HasColumnType("real");

                    b.Property<float>("Str8")
                        .HasColumnType("real");

                    b.Property<float>("Str9")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.ToTable("Scalings");
                });

            modelBuilder.Entity("EldenRingArKalculator.Models.Weapon", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArcScaling")
                        .HasColumnType("int");

                    b.Property<int>("DexScaling")
                        .HasColumnType("int");

                    b.Property<int>("FaiScaling")
                        .HasColumnType("int");

                    b.Property<float>("Fire")
                        .HasColumnType("real");

                    b.Property<float>("Holy")
                        .HasColumnType("real");

                    b.Property<int>("IntScaling")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<float>("Light")
                        .HasColumnType("real");

                    b.Property<float>("Mag")
                        .HasColumnType("real");

                    b.Property<float>("Phys")
                        .HasColumnType("real");

                    b.Property<int>("StrScaling")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
